SETTINGS_PRIORITY = 0

PYBPOD_SERIAL_PORT       = '/dev/ttyACM38'
PYBPOD_NET_PORT          = 36001

BPOD_BNC_PORTS_ENABLED = [True, True]
BPOD_WIRED_PORTS_ENABLED = [True, True]
BPOD_BEHAVIOR_PORTS_ENABLED = [True, True, True, True, True, True, True, True]

PYBPOD_API_LOG_LEVEL = None
PYBPOD_API_LOG_FILE  = None

PYBPOD_API_STREAM2STDOUT = True
PYBPOD_API_ACCEPT_STDIN  = True

PYBPOD_PROTOCOL 	= 'stage3_alexis'
PYBPOD_CREATOR 		= '["Alexis", "da0ec0f2-1611-4456-ae0b-0d61915c4952", "local"]'
PYBPOD_PROJECT 		= 'pv_nmdar_eranet'
PYBPOD_EXPERIMENT 	= '2AFC'
PYBPOD_BOARD 		= 'Bpod8'
PYBPOD_SETUP 		= 'Test'
PYBPOD_SESSION 		= 'Test_stage3_alexis_20210317-172700'
PYBPOD_SESSION_PATH = '/home/setup2/pv_nmdar_eranet/experiments/2AFC/setups/Test/sessions/Test_stage3_alexis_20210317-172700'
PYBPOD_SUBJECTS 	= ["['Test', 'd0d2ad0d-bc67-4aa0-910f-61c0399d2c97']"]
PYBPOD_SUBJECT_EXTRA = ''
PYBPOD_USER_EXTRA = ''


TARGET_BPOD_FIRMWARE_VERSION = '22'

#import logging
#PYBPOD_API_LOG_LEVEL = logging.DEBUG
#PYBPOD_API_LOG_FILE  = 'pybpod-api.log'

PYBPOD_VARSNAMES = ['VAR_AW','VAR_TRIAL','VAR_TIMEOUT','VAR_FIXATION','VAR_STAGE','VAR_SUBSTAGE','VAR_MOTOR','VAR_REC']
VAR_AW = 0.0
VAR_TRIAL = 1000.0
VAR_TIMEOUT = 2.0
VAR_FIXATION = 0.0
VAR_STAGE = 4.0
VAR_SUBSTAGE = 3.0
VAR_MOTOR = 4.0
VAR_REC = 0.0