# import turtle
import math

# bob = turtle.Turtle()

from mypolygon import arc_v2

# r = 20

def draw_a(t, r):
    t.pu()
    t.fd(2 / 3 * r)
    t.pd()

    arc_v2(t, 2 / 3 * r, 360)
    t.pu()
    arc_v2(t, 2 / 3 * r, 90)
    t.pd()
    t.fd(0.66 * r)
    arc_v2(t, 2 / 3 * r, 180)
    t.lt(90)
    t.pu()
    t.fd(2 * 2 / 3 * r)
    t.rt(90)
    t.fd(2 * 2 / 3 * r)
    t.lt(90)

def draw_b(t, r):
    t.pu()
    t.fd(r)
    t.pd()
    arc_v2(t, r, 360)
    t.pu()
    t.bk(r)
    t.pd()
    t.lt(90)
    t.fd(3 * r)
    t.pu()
    t.bk(3 * r)
    t.rt(90)
    t.fd(2 * r)

def draw_c(t, r):
    t.pu()
    t.fd(r)
    arc_v2(t, r, 180)
    t.bk(r / 2)
    t.pd()
    t.fd(r / 2)
    arc_v2(t, r, 180)
    t.fd(r / 2)

def draw_d(t, r):
    t.pu()
    t.fd(r)
    t.pd()
    arc_v2(t, r, 360)
    t.pu()
    t.fd(r)
    t.pd()
    t.lt(90)
    t.fd(3 * r)
    t.pu()
    t.bk(3 * r)
    t.rt(90)

def draw_e(t, r):
    t.pu()
    t.fd(r)
    arc_v2(t, r, 90)
    t.pd()
    arc_v2(t, r, 270)
    t.pu()
    arc_v2(t, r, 90)
    t.pd()
    t.lt(90)
    t.fd(2 * r)
    t.lt(90)
    t.pu()
    arc_v2(t, r, 90)
    t.fd(r)

def draw_f(t, r):
    t.lt(90)
    t.fd(2 * r)
    t.pu()
    t.rt(90)
    t.bk(r)
    t.pd()
    t.fd(2 * r)
    t.rt(90)
    t.pu()
    t.fd(r)
    t.lt(90)
    arc_v2(t, r, 180)
    t.pd()
    arc_v2(t, r, 90)
    t.pu()
    t.fd(2 * r)
    t.lt(90)
    t.fd(r)

def draw_g(t, r):
    t.pu()
    t.fd(r)
    t.pd()
    arc_v2(t, r, 360)
    t.pu()
    t.fd(r)
    t.rt(90)
    t.bk(r)
    t.pd()
    t.fd(r)
    t.pu()
    t.fd(r)
    t.lt(90)
    t.bk(r)
    arc_v2(t, r, 90)
    t.pu()
    arc_v2(t, r, 180)
    t.pd()
    arc_v2(t, r, 180)
    t.rt(90)

def draw_h(t, r):
    t.lt(90)
    t.fd(3 * r)
    t.pu()
    t.bk(4 * r)
    t.rt(90)
    t.fd(r)
    t.lt(90)
    t.rt(90)
    arc_v2(t, r, 90)
    t.pd()
    arc_v2(t, r, 180)
    t.lt(90)
    t.pu()
    t.fd(2 * r)

def draw_i(t, r):
    t.lt(90)
    t.fd(2 * r)
    t.pu()
    t.fd(r / 2)
    t.rt(90)
    t.pd()
    arc_v2(t, r / 4, 360)
    t.rt(90)
    t.pu()
    t.fd(2 * r + r / 2)
    t.lt(90)

def draw_j(t, r):
    # insert draw_i code at the end
    t.pu()
    t.bk(r)
    t.rt(90)
    t.fd(r)
    t.lt(90)
    t.pd()
    arc_v2(t, r, 90)

    # insert draw_i code at the end
    t.fd(2 * r)
    t.pu()
    t.fd(r / 2)
    t.rt(90)
    t.pd()
    arc_v2(t, r / 4, 360)
    t.rt(90)
    t.pu()
    t.fd(2 * r + r / 2)
    t.lt(90)

def draw_k(t, r):
    t.lt(90)
    t.fd(3 * r)
    t.pu()
    t.bk(3 * r)
    t.rt(90)
    t.fd(r + r / 2)
    arc_v2(t, r + r / 2, 180)
    t.pd()
    arc_v2(t, r + r / 2, 180)

def draw_l(t, r):
    t.lt(90)
    t.fd(3 * r)
    t.pu()
    t.bk(3 * r)
    t.rt(90)

def draw_m(t, r):
    t.lt(90)
    t.fd(2 * r)
    t.pu()
    t.bk(2 * r)
    t.rt(90)
    t.fd(r)
    arc_v2(t, r, 90)
    t.pd()
    arc_v2(t, r, 180)
    t.pu()
    arc_v2(t, r, 180)

    t.bk(r)
    t.pd()
    t.fd(r)
    t.pu()
    t.bk(r)
    t.rt(90)
    t.fd(r)
    arc_v2(t, r, 90)
    t.pd()
    arc_v2(t, r, 180)
    t.pu()
    arc_v2(t, r, 180)
    t.pd()
    t.bk(r)

    t.rt(90)

def draw_n(t, r):
    t.lt(90)
    t.fd(2 * r)
    t.pu()
    t.bk(2 * r)
    t.rt(90)
    t.fd(r)
    arc_v2(t, r, 90)
    t.pd()
    arc_v2(t, r, 180)
    t.pu()
    arc_v2(t, r, 180)
    t.bk(r)
    t.pd()
    t.fd(r)
    t.pu()
    t.bk(r)
    t.rt(90)

def draw_o(t, r):
    t.pu()
    t.fd(r)
    t.pd()
    arc_v2(t, r, 360)
    t.pu()
    t.fd(r)

def draw_p(t, r):
    t.pu()
    t.fd(r)
    t.pd()
    arc_v2(t, r, 360)
    t.pu()
    t.bk(r)
    t.rt(90)
    t.bk(r)
    t.pd()
    t.fd(2 * r)
    t.pu()
    t.bk(r)
    t.lt(90)
    t.fd(2 * r)

def draw_q(t, r):
    t.pu()
    t.fd(r)
    t.pd()
    arc_v2(t, r, 360)
    t.pu()
    t.fd(r)
    t.rt(90)
    t.bk(r)
    t.pd()
    t.fd(2 * r)
    t.pu()
    t.bk(r)
    t.lt(90)

def draw_r(t, r):
    t.lt(90)
    t.fd(2 * r)
    t.pu()
    t.bk(2 * r)
    t.rt(90)
    t.fd(r)
    arc_v2(t, r, 180)
    t.pd()
    arc_v2(t, r, 90)
    t.pu()
    arc_v2(t, r, 90)

def draw_s(t, r):
    t.pu()
    t.fd(r / 2)
    t.pd()
    t.pu()
    t.bk(r / 2)
    t.pd()
    t.fd(r / 2)
    arc_v2(t, r / 2, 180)
    t.pu()
    t.rt(180)
    arc_v2(t, r / 2, 180)
    t.pd()
    arc_v2(t, r / 2, 180)
    t.pu()
    arc_v2(t, r / 2, 180)
    t.pd()
    t.bk(r / 2)
    t.lt(90)
    t.pu()
    t.fd(2 * r)
    t.lt(90)

def draw_t(t, r):
    t.lt(90)
    t.fd(3 * r)
    t.pu()
    t.bk(r)
    t.rt(90)
    t.bk(r)
    t.pd()
    t.fd(2 * r)
    t.rt(90)
    t.pu()
    t.fd(2 * r)
    t.lt(90)

def draw_u(t, r):
    t.pu()
    t.fd(r)
    t.pd()
    arc_v2(t, r, 90)
    t.fd(r)
    t.lt(90)
    t.pu()
    t.fd(2 * r)
    t.lt(90)
    t.pd()
    t.fd(r)
    arc_v2(t, r, 90)
    t.pu()
    t.fd(r)

def draw_v(t, r):
    t.pu()
    t.fd(r)
    t.pd()
    c = math.sqrt(r**2 + (2 * r)**2)  # Pythagore's Theorem to find the diagonal length
    sin_alpha = (2 * r) / c # sine of the interested angle
    inv_sin_alpha = math.asin(sin_alpha) # inversion of sine alpha
    alpha = math.degrees(inv_sin_alpha) # alpha angle in degrees
    t.lt(alpha)
    t.fd(c)
    t.pu()
    t.bk(c)
    t.lt((90 - alpha) * 2)
    t.pd()
    t.fd(c)
    t.pu()
    t.bk(c)
    t.rt((90 - alpha) * 2 + alpha)
    t.fd(r)

def draw_w(t, r):
    t.pu()
    t.fd(r)
    t.pd()
    c = math.sqrt(r**2 + (2 * r)**2)  # Pythagore's Theorem to find the diagonal length
    sin_alpha = (2 * r) / c # sine of the interested angle
    inv_sin_alpha = math.asin(sin_alpha) # inversion of sine alpha
    alpha = math.degrees(inv_sin_alpha) # alpha angle in degrees
    t.lt(alpha)
    t.fd(c)
    t.pu()
    t.bk(c)
    t.lt((90 - alpha) * 2)
    t.pd()
    t.fd(c)
    t.pu()
    t.bk(c)
    t.rt((90 - alpha) * 2 + alpha)
    t.fd(r)

    t.pd()
    t.lt(alpha)
    t.fd(c)
    t.pu()
    t.bk(c)
    t.lt((90 - alpha) * 2)
    t.pd()
    t.fd(c)
    t.pu()
    t.bk(c)
    t.rt((90 - alpha) * 2 + alpha)
    t.fd(r)

def draw_x(t, r):
    arc_v2(t, r, 180)
    t.pu()
    arc_v2(t, r, 180)
    t.fd(2 * r)
    arc_v2(t, r, 180)
    t.pd()
    arc_v2(t, r, 180)

def draw_y(t, r):
    t.pu()
    t.fd(r)
    t.pd()
    arc_v2(t, r, 90)
    t.fd(r)
    t.pu()
    arc_v2(t, r, 180)
    t.pd()
    t.fd(r)
    arc_v2(t, r, 90)
    t.pu()
    t.fd(r)
    t.rt(90)
    t.bk(r)
    t.pd()
    t.fd(r)
    t.pu()
    t.fd(r)
    t.lt(90)
    t.bk(r)
    arc_v2(t, r, 90)
    t.pu()
    arc_v2(t, r, 180)
    t.pd()
    arc_v2(t, r, 180)
    t.rt(90)

def draw_z(t, r):
    t.fd(2 * r)
    t.pu()
    t.bk(2 * r)
    c = math.sqrt((2 * r)**2 + (2 * r)**2) # Pythagore's Theorem to find the diagonal length
    sin_alpha = (2 * r) / c # sine of the interested angle
    inv_sin_alpha = math.asin(sin_alpha) # inversion of sine alpha
    alpha = math.degrees(inv_sin_alpha) # alpha angle in degrees
    t.lt(alpha)
    t.pd()
    t.fd(c)
    t.rt(alpha)
    t.bk(2 * r)
    t.rt(90)
    t.pu()
    t.fd(2 * r)
    t.lt(90)
    t.fd(2 * r)

def skip(t, r):
    """lift the pen and move"""
    t.pu()
    t.fd(r)
    t.pd()